Removed unused imports. Fixed undefined reference to "getpackage" (from nose.util).
git-svn-id: http://svn.scipy.org/svn/numpy/trunk@5823 94b884b6-d6fd-0310-90d3-974f1d3f35e1